services:
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: ployd
      POSTGRES_PASSWORD: ployd
      POSTGRES_DB: ployd
    ports:
      - "5432:5432"
    networks:
      - ployd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ployd"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  ployd:
    container_name: ployd
    image: ghcr.io/dmkk3r/ployd/ployd:latest
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ployd;Username=ployd;Password=ployd
    restart: always
    networks:
      - ployd
    depends_on:
      postgres:
        condition: service_healthy
networks:
  ployd:
    driver: bridge
