// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ployd.Store;

#nullable disable

namespace Ployd.Store.Migrations
{
    [DbContext(typeof(PloydStoreContext))]
    partial class PloydStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("DeploymentEntityDeploymentTargetEntity", b =>
                {
                    b.Property<Guid>("DeploymentTargetsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentsId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeploymentTargetsId", "DeploymentsId");

                    b.HasIndex("DeploymentsId");

                    b.ToTable("DeploymentEntityDeploymentTargetEntity");
                });

            modelBuilder.Entity("Ployd.Store.Entities.DeploymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentSourceId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Ployd.Store.Entities.DeploymentSourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeploymentSourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeploymentSources");
                });

            modelBuilder.Entity("Ployd.Store.Entities.DeploymentTargetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeploymentTargetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeploymentTargets");
                });

            modelBuilder.Entity("DeploymentEntityDeploymentTargetEntity", b =>
                {
                    b.HasOne("Ployd.Store.Entities.DeploymentTargetEntity", null)
                        .WithMany()
                        .HasForeignKey("DeploymentTargetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ployd.Store.Entities.DeploymentEntity", null)
                        .WithMany()
                        .HasForeignKey("DeploymentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ployd.Store.Entities.DeploymentEntity", b =>
                {
                    b.HasOne("Ployd.Store.Entities.DeploymentSourceEntity", "DeploymentSource")
                        .WithMany("Deployments")
                        .HasForeignKey("DeploymentSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeploymentSource");
                });

            modelBuilder.Entity("Ployd.Store.Entities.DeploymentSourceEntity", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
